name: studentapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  firebase_auth: ^0.15.3
  flutter_email_sender: ^2.2.2
  mailer: ^3.0.4
  url_launcher: ^5.4.1
  cloud_firestore: ^0.13.2+2
  flutter_spinkit: ^4.1.2
  provider: ^4.0.4
  image_picker: ^0.6.3+4
  video_player:
  chewie: ^0.9.10
  flutter_speed_dial: ^1.2.5
  camera: ^0.5.7+4
  fluttertoast: ^4.0.1
  path_provider: ^1.6.5
  file_picker: ^1.5.0+2
  flutter_form_builder: ^3.13.5
  firebase_storage:
  flutter_ffmpeg:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: UbuntuCondensed
      fonts:
        - asset: assets/fonts/UbuntuCondensed-Regular.ttf
    - family: Patua_One
      fonts:
        - asset: assets/fonts/PatuaOne-Regular.ttf
    - family: Russo_One
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
    - family: Indie_Flower
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
  assets:
    - assets/sound/2.mp3
    - assets/sound/3.mp3
    - assets/sound/4.mp3
    - assets/sound/5.mp3
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/1.png
    - assets/images/1.jpg
    - assets/images/4.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
